repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy-nrf7002dk
        name: cargo clippy
        entry: cargo clippy --features "nrf7002dk" --target=thumbv8m.main-none-eabihf --no-default-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy-nrf5340dk
        name: cargo clippy
        entry: cargo clippy --features "nrf5340dk" --target=thumbv8m.main-none-eabihf --no-default-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
