[package]
name = "si47x_radio"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-futures = { version = "0.1.2" }
embassy-sync = { version = "0.7.2", features = ["log"] }
embassy-nrf = { version = "0.8.0", features = ["log", "nrf5340-app-s", "time-driver-rtc1", "gpiote", "time"], optional = true }
embassy-embedded-hal = { version = "0.5.0" }
ekv = { version = "1.0.0", features = ["crc"] }
embedded-io-async = { version = "0.6.1" }
embedded-io = { version = "0.6.0" }
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"
embedded-cli = "0.2.1"
embedded-hal = { version = "1.0" }
embedded-hal-async = { version = "1.0" }
static_cell = "2"
panic-probe = { version = "1.0.0", features = ["print-rtt"] }
rtt-target = "0.5.0"
si473x = { git = "https://github.com/apapkovskiy/si473x-rs.git" }
heapless = "0.9.2"
log = "0.4.29"
linkme = "0.3.35"
num-traits = { version = "0.2.19", default-features = false }

[features]
default = []
nrf = ["dep:embassy-nrf"]
nrf5340dk = ["nrf"]
nrf7002dk = ["nrf"]
host = []

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embassy-executor = { version = "0.9.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "log"] }
critical-section = "1.2.0"
embassy-time = { version = "0.5.0", features = ["log"] }
nrf-pac = { version = "0.3.0", features = ["nrf5340-app"] }

[target.'cfg(any(windows, unix))'.dependencies]
async-std = "1.13.2"
embassy-executor = { version = "0.9.0", features = ["arch-std", "executor-thread", "log"] }
critical-section = { version = "1.2.0", features = ["std"] }
embassy-time = { version = "0.5.0", features = ["std", "log"] }
libc = "0.2.180"

[patch.crates-io]
ekv = { git = "https://github.com/embassy-rs/ekv", rev = "a7d0ce35b7d989f621575d838d211e546a54d2eb" }
